name: Business_Monsters
description: Mobile platform that uses gamification to empower entrepreuners.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: 
  slimy_card:
  flutter_screenutil: ^1.0.2
  font_awesome_flutter: ^8.5.0
  flutter_staggered_animations: "^0.1.2"
  curved_navigation_bar:
  clay_containers:
  custom_switch: 
    git: 
      url: https://github.com/MarcioQuimbundo/custom_switch_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/profile_pic.png
    - assets/coin.png
    - assets/calculator.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
