name: Business_Monsters
description: Mobile platform that uses gamification to empower entrepreuners.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_youtube: "^2.0.0"
  gradient_app_bar: ^0.1.3
  provider: 
  slimy_card:
  flutter_screenutil: ^1.0.2
  font_awesome_flutter: ^8.5.0
  flutter_staggered_animations: "^0.1.2"
  curved_navigation_bar:
  clay_containers:
  url_launcher: ^3.0.3
  custom_switch: 
    git: 
      url: https://github.com/MarcioQuimbundo/custom_switch_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/profile_pic.png
    - assets/next_profile.png
    - assets/coin.png
    - assets/calculator.png
    - assets/cloud.png
    - assets/curso.png
    - assets/party.png
    - assets/playbutton.png
    - assets/sword.png
    - assets/book.png

  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Squada One
      fonts:
        - asset: assets/fonts/SquadaOne-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
